### PR TITLE
use git to download drupal 8

### PR DESCRIPTION
**Pull request by franxo**
Use git to clone drupal 8 repository, use 8.2.x version and set default password to site installation

### CODE REVIEW

**Comment by carlosreig** [comment]
Thanks @franxo! That's a good idea :)

The only thing I would change is the `--branch 8.2.x` parameter. I don't want to change the installation script for each new Drupal 8 version.

**Comment by carlosreig** [comment]
I have just checked if you just remove the `--branch` parameter, then git will clone the last development branch.

**Comment by carlosreig** [comment]
I merge it because @DavidHernandez is going to do another pull request applying the change.

Thanks @franxo and @DavidHernandez!

**Comment by franxo** [comment]
Well done!

**Pull request merged**
