### PR TITLE
Makes Dockerfile work

### PR DESCRIPTION
**Pull request by sulav**

### CODE REVIEW

**Review by jasonmce — APPROVED** [review]
This fixed the build step for me when upgraded to 1.13.1.  Looks like it should be backwards compatible.

**Comment by carlosreig** [comment]
Hi @sulav, @jasonmce,

Thanks for contributing to the repo! :)

I have checked that the new syntax works with v1.13.1. I just have two doubts:

- Why do you remove Mailhog as part of the PR? Is it also failing? Unfortunately, I cannot test the full build because I don't have a good Internet connection right now.
- Why the Apache's port has been changed?

Thanks again :)

Have a nice day!
Carlos

**Comment by sulav** [comment]
Hi @carlosreig 

Sorry, that was my fault. I only meant to commit apache/Dockerfile and not docker-compose. The stuff were removed from docker-compose as a test because I wasn't using mailhog. Updated PR coming soon.

Edit: PR Updated, please give this another look.
Thanks,
Sulav

**Review by jasonmce — APPROVED** [review]
Thanks man, much simpler.

**Comment by carlosreig** [comment]
Thanks to both of you!

:+1:

**Pull request merged**
